/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../java/jni.h"
#include "funcs.h"
#include "..\misc\util.h"
/* Header for class sunw_util_AZJni_SendStringClass */

//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#ifndef _Included_sunw_util_AZJni_SendStringClass
#define _Included_sunw_util_AZJni_SendStringClass
//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#ifdef __cplusplus
extern "C" {
//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#if
/*
 * Class:     sunw_util_AZJni_SendStringClass
 * Method:    sendString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sunw_util_AZJni_00024SendStringClass_sendString
  (JNIEnv* env, jclass, jstring nameWindow, jstring chars)
{
	DbgMsg("Enter from java");
	char* nameWindow2 = ToAnsi( (WCHAR*)env->GetStringChars( nameWindow, NULL ) );
	char* chars2 = ToAnsi( (WCHAR*)env->GetStringChars( chars, NULL ) );
	SendKeys( nameWindow2, chars2 );
	u_free(nameWindow2);
	u_free(chars2);
}

//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#ifdef __cplusplus
}
//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#if
//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#if
